name: List scores
description: ""
inputs:
  report-path:
    description: 'Report path'
    required: false
    default: 'report.md'
  group-size:
    description: 'Group size'
    required: false
    type: number
    default: 3
runs:
  using: "composite"
  steps:
    - name: Process
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        REPORTPATH: ${{ inputs.report-path }}
        GROUPSIZE: ${{ inputs.group-size }}
      run: |
        python3 list.py
